// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ColumnInfo defines model for ColumnInfo.
type ColumnInfo struct {
	Name     string `json:"name"`
	Nullable *bool  `json:"nullable,omitempty"`
	Type     string `json:"type"`
}

// Connection defines model for Connection.
type Connection struct {
	// Config Driver-specific connection configuration
	Config      json.RawMessage `json:"config"`
	CreatedAt   time.Time       `json:"created_at"`
	CreatedBy   *string         `json:"created_by,omitempty"`
	Description *string         `json:"description,omitempty"`
	Id          int64           `json:"id"`
	IsActive    bool            `json:"is_active"`
	Name        string          `json:"name"`
	Tags        *[]string       `json:"tags,omitempty"`

	// Type Datasource type identifier (e.g. "postgresql", "clickhouse")
	Type      string    `json:"type"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ConnectionListResponse defines model for ConnectionListResponse.
type ConnectionListResponse struct {
	Data []Connection `json:"data"`
}

// ConnectionResponse defines model for ConnectionResponse.
type ConnectionResponse struct {
	Data Connection `json:"data"`
}

// ConnectionSchemaResponse defines model for ConnectionSchemaResponse.
type ConnectionSchemaResponse struct {
	Data map[string]interface{} `json:"data"`
}

// ConnectionStats defines model for ConnectionStats.
type ConnectionStats struct {
	ActiveCount int64            `json:"active_count"`
	CountByType map[string]int64 `json:"count_by_type"`
	TotalCount  int64            `json:"total_count"`
}

// ConnectionStatsResponse defines model for ConnectionStatsResponse.
type ConnectionStatsResponse struct {
	Data ConnectionStats `json:"data"`
}

// ConnectionTestResponse defines model for ConnectionTestResponse.
type ConnectionTestResponse struct {
	Data ConnectionTestResult `json:"data"`
}

// ConnectionTestResult defines model for ConnectionTestResult.
type ConnectionTestResult struct {
	IsConnected bool       `json:"is_connected"`
	LatencyMs   *int64     `json:"latency_ms,omitempty"`
	Message     string     `json:"message"`
	TestedAt    *time.Time `json:"tested_at,omitempty"`
}

// ConnectionTypesResponse defines model for ConnectionTypesResponse.
type ConnectionTypesResponse struct {
	Data []string `json:"data"`
}

// CreateConnectionRequest defines model for CreateConnectionRequest.
type CreateConnectionRequest struct {
	Config      map[string]interface{} `json:"config"`
	CreatedBy   *string                `json:"created_by,omitempty"`
	Description *string                `json:"description,omitempty"`
	Name        string                 `json:"name"`
	Tags        *[]string              `json:"tags,omitempty"`
	Type        string                 `json:"type"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// QueryRequest defines model for QueryRequest.
type QueryRequest struct {
	Limit  *int           `json:"limit,omitempty"`
	Params *[]interface{} `json:"params,omitempty"`
	Query  string         `json:"query"`
}

// QueryResponse defines model for QueryResponse.
type QueryResponse struct {
	Data QueryResult `json:"data"`
}

// QueryResult defines model for QueryResult.
type QueryResult struct {
	Columns []ColumnInfo    `json:"columns"`
	Rows    [][]interface{} `json:"rows"`
}

// TestConnectionRequest defines model for TestConnectionRequest.
type TestConnectionRequest struct {
	Config map[string]interface{} `json:"config"`
	Type   string                 `json:"type"`
}

// UpdateConnectionRequest defines model for UpdateConnectionRequest.
type UpdateConnectionRequest struct {
	Config      *map[string]interface{} `json:"config,omitempty"`
	Description *string                 `json:"description,omitempty"`
	IsActive    *bool                   `json:"is_active,omitempty"`
	Name        *string                 `json:"name,omitempty"`
	Tags        *[]string               `json:"tags,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// NotImplemented defines model for NotImplemented.
type NotImplemented = ErrorResponse

// ListConnectionsParams defines parameters for ListConnections.
type ListConnectionsParams struct {
	// Type Filter by datasource type
	Type *string `form:"type,omitempty" json:"type,omitempty"`

	// IsActive Filter by active status
	IsActive *bool `form:"is_active,omitempty" json:"is_active,omitempty"`

	// CreatedBy Filter by creator
	CreatedBy *string `form:"created_by,omitempty" json:"created_by,omitempty"`
}

// CreateConnectionJSONRequestBody defines body for CreateConnection for application/json ContentType.
type CreateConnectionJSONRequestBody = CreateConnectionRequest

// TestConnectionConfigJSONRequestBody defines body for TestConnectionConfig for application/json ContentType.
type TestConnectionConfigJSONRequestBody = TestConnectionRequest

// UpdateConnectionJSONRequestBody defines body for UpdateConnection for application/json ContentType.
type UpdateConnectionJSONRequestBody = UpdateConnectionRequest

// QueryConnectionJSONRequestBody defines body for QueryConnection for application/json ContentType.
type QueryConnectionJSONRequestBody = QueryRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get connection statistics
	// (GET /connection-stats)
	GetConnectionStats(c *gin.Context)
	// List supported connection types
	// (GET /connection-types)
	ListConnectionTypes(c *gin.Context)
	// List all connections
	// (GET /connections)
	ListConnections(c *gin.Context, params ListConnectionsParams)
	// Create a connection
	// (POST /connections)
	CreateConnection(c *gin.Context)
	// Test a connection config without saving
	// (POST /connections/test)
	TestConnectionConfig(c *gin.Context)
	// Delete a connection
	// (DELETE /connections/{id})
	DeleteConnection(c *gin.Context, id int64)
	// Get a connection by ID
	// (GET /connections/{id})
	GetConnection(c *gin.Context, id int64)
	// Update a connection
	// (PUT /connections/{id})
	UpdateConnection(c *gin.Context, id int64)
	// Execute a query through a connection
	// (POST /connections/{id}/query)
	QueryConnection(c *gin.Context, id int64)
	// Get datasource schema for a connection
	// (GET /connections/{id}/schema)
	GetConnectionSchema(c *gin.Context, id int64)
	// Test a connection
	// (POST /connections/{id}/test)
	TestConnection(c *gin.Context, id int64)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetConnectionStats operation middleware
func (siw *ServerInterfaceWrapper) GetConnectionStats(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetConnectionStats(c)
}

// ListConnectionTypes operation middleware
func (siw *ServerInterfaceWrapper) ListConnectionTypes(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListConnectionTypes(c)
}

// ListConnections operation middleware
func (siw *ServerInterfaceWrapper) ListConnections(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListConnectionsParams

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", c.Request.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter type: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "is_active" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "is_active", c.Request.URL.Query(), &params.IsActive, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter is_active: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "created_by" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "created_by", c.Request.URL.Query(), &params.CreatedBy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter created_by: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListConnections(c, params)
}

// CreateConnection operation middleware
func (siw *ServerInterfaceWrapper) CreateConnection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateConnection(c)
}

// TestConnectionConfig operation middleware
func (siw *ServerInterfaceWrapper) TestConnectionConfig(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.TestConnectionConfig(c)
}

// DeleteConnection operation middleware
func (siw *ServerInterfaceWrapper) DeleteConnection(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteConnection(c, id)
}

// GetConnection operation middleware
func (siw *ServerInterfaceWrapper) GetConnection(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetConnection(c, id)
}

// UpdateConnection operation middleware
func (siw *ServerInterfaceWrapper) UpdateConnection(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateConnection(c, id)
}

// QueryConnection operation middleware
func (siw *ServerInterfaceWrapper) QueryConnection(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.QueryConnection(c, id)
}

// GetConnectionSchema operation middleware
func (siw *ServerInterfaceWrapper) GetConnectionSchema(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetConnectionSchema(c, id)
}

// TestConnection operation middleware
func (siw *ServerInterfaceWrapper) TestConnection(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.TestConnection(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/connection-stats", wrapper.GetConnectionStats)
	router.GET(options.BaseURL+"/connection-types", wrapper.ListConnectionTypes)
	router.GET(options.BaseURL+"/connections", wrapper.ListConnections)
	router.POST(options.BaseURL+"/connections", wrapper.CreateConnection)
	router.POST(options.BaseURL+"/connections/test", wrapper.TestConnectionConfig)
	router.DELETE(options.BaseURL+"/connections/:id", wrapper.DeleteConnection)
	router.GET(options.BaseURL+"/connections/:id", wrapper.GetConnection)
	router.PUT(options.BaseURL+"/connections/:id", wrapper.UpdateConnection)
	router.POST(options.BaseURL+"/connections/:id/query", wrapper.QueryConnection)
	router.GET(options.BaseURL+"/connections/:id/schema", wrapper.GetConnectionSchema)
	router.POST(options.BaseURL+"/connections/:id/test", wrapper.TestConnection)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xaX3PiNhD/Khq1D+2MA6GX9oG3u9xdh+n1mibXvjQZRtiL0dWWHEkmx2T47h1JNki2",
	"MSaA06eALe2ufvvvtyLPOORpxhkwJfH4GQuQGWcSzJd3JLqFxxyk0t9CzhQw85FkWUJDoihnw6+SM/1M",
	"hgtIif70vYA5HuPvhlvRQ/tWDj8IwcVtoQSv1+sARyBDQTMtDI+1TlQqXQd4whQIRhKzrz8rSrXoDsQS",
	"BLLq1wH+zNVHnrOoP1M+c4WsSqt+kmYJpMAU9GyEq1ivKDZr2dc8yVM2YXOuv2WCZyAUtUHESAr6r1pl",
	"gMdYKkFZrM/C8iQhs8R9OeM8AcL0W/uktm0dYAGPORX69P9Y4cXih3IT5rOvEJrwueaMQWgPUTUs5GxO",
	"YwNcFFG9hiQ3zgolcqji8F7QJYgLmUFI5zRE4UY+suJyYfDHVVsC/O0i5hfFQ+2dwS15+h2kJDFoS0MB",
	"REE0JcaVcy5S/QlHRMGFottTugiWe2arRoA90xve08hTRZn65WqrhjIFMZigp3JKQkWXO1y108OKxAZp",
	"qiCVzSvsAyIEWbler6BOFJE8FyEgvQDRCJiicwoC/QCDeIDuccaligXIx+QeB+gehwkN/13wXMI9/rEJ",
	"uzyLDsS7Eno0woEXf0EZUS5gnmM9re3h+olKtUnIWuhGRBEP2LbkdnKghnjlTEZuu2H7jepqy+G674yU",
	"/Ra05XNF/AuMUMS2Sl+39fc05DlTHdPKrJ3OVtMy6pvt7iSrZrDiiiQHmFMBwt0e+IerGt4BrlMFjcX+",
	"BU77Al3SqZsRhaw8UUdYonfX7KByWjQU29vrpTYhCli4mqZd4yItOkxj8QV5XAV0zd2q2nP+VQbygMq2",
	"p2V0doCpwm4Z2/Dal7CCmvwjW3HZQlPKPgGL1QKPR8EpG2qr4BZStWlqTaD6tLEGJZScvV2dXdYk/88c",
	"xGqnpxKaUuWId6I+I4KkHlIN0Dxq6fvNs8tazDumqpQiDiom7qaG+NVUXB7ADjbUvQEjwZ98US14tiZm",
	"aVYhsulYujKeL0Ffkgj7M+Avw+fOZ/VeCt+NmZ+4rNT5hn5Ei/Gvzt3R33xFYhDo9sPdF/T2ZqKrC1V6",
	"9PPf21dLENJuvhyMBpdaP8+AkYziMX4zuBy8wTrF1cLYOtzOYBey5GYxGB9ofM08NonwGP8KqkolAv/C",
	"46fLy5PN1LsoUMN0/cdv+ow/W+VNMjdGDv37EDOG52lKdCHT53MHUg0GlYqG+pjWxToPy/cSP+jtLnza",
	"qbvh0yNJpY/3g59PGc6Hnz4gknmWcaEgcqFUxWG7oNgVQImLPgUKhJZazZyPNFEg0GyFIn/+1QOmXmA7",
	"U5nlZbXaolsrbrs12CJiQiaXO+S7Q21NyabotGkxJImLHfIdCtV2iodeYs6bv88cciRJUOjFRXOcBeaW",
	"ox5XVW6LbRcDqd7xaHU6cHZQ6LXfNnUnW9d8NDqDj9r8Y401d6ZXXZzkXHWfwq9WPSKOX7uWj6EqCUSj",
	"s32WdF3eOJ3D4c2ErJO7z9IGoEtKvoa3tWWer4vLYPRE1YLnCkmy1MWrawQ802htmVQCCuox8N48ryS8",
	"h/9VnYh95ui6cMgpzmxt6BbhQQc+1g+V6BI/V/uB2fwKdCra5gXPbIUm79u6gM8aTC/VdNhp1RGu5qjb",
	"UvdfBj4EOMsbXFadd85UeXaNVa9We85Sd/oPNYvry9qSLkrDzZ1JTzHY2ALN/cfZY9C7fOo58PybpVeO",
	"uVGnDbVfhzdB9+EbhLmJOhM9SC0Ez+PFEVG4BbHDnG/X9jPo+79PnbLHHOsE3WScMdLajuZcdO3gfSR8",
	"o7M3dPgVK47PhPH/iu723UNqZHd37up95v9nmq433t5M0HKEA5yLBI/xkGR0uBxh7YRCXONVYhHADl1K",
	"CSOxiXrnLsExZP2w/i8AAP//do+mueYkAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
