// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AIConfigProvider.
const (
	AIConfigProviderClaude  AIConfigProvider = "claude"
	AIConfigProviderCopilot AIConfigProvider = "copilot"
	AIConfigProviderOllama  AIConfigProvider = "ollama"
	AIConfigProviderOpenai  AIConfigProvider = "openai"
)

// Valid indicates whether the value is a known member of the AIConfigProvider enum.
func (e AIConfigProvider) Valid() bool {
	switch e {
	case AIConfigProviderClaude:
		return true
	case AIConfigProviderCopilot:
		return true
	case AIConfigProviderOllama:
		return true
	case AIConfigProviderOpenai:
		return true
	default:
		return false
	}
}

// Defines values for AIConfigHistoryAction.
const (
	AIConfigHistoryActionActivated AIConfigHistoryAction = "activated"
	AIConfigHistoryActionCreated   AIConfigHistoryAction = "created"
	AIConfigHistoryActionDeleted   AIConfigHistoryAction = "deleted"
	AIConfigHistoryActionUpdated   AIConfigHistoryAction = "updated"
)

// Valid indicates whether the value is a known member of the AIConfigHistoryAction enum.
func (e AIConfigHistoryAction) Valid() bool {
	switch e {
	case AIConfigHistoryActionActivated:
		return true
	case AIConfigHistoryActionCreated:
		return true
	case AIConfigHistoryActionDeleted:
		return true
	case AIConfigHistoryActionUpdated:
		return true
	default:
		return false
	}
}

// Defines values for ConnectionHistoryAction.
const (
	ConnectionHistoryActionCreated ConnectionHistoryAction = "created"
	ConnectionHistoryActionDeleted ConnectionHistoryAction = "deleted"
	ConnectionHistoryActionUpdated ConnectionHistoryAction = "updated"
)

// Valid indicates whether the value is a known member of the ConnectionHistoryAction enum.
func (e ConnectionHistoryAction) Valid() bool {
	switch e {
	case ConnectionHistoryActionCreated:
		return true
	case ConnectionHistoryActionDeleted:
		return true
	case ConnectionHistoryActionUpdated:
		return true
	default:
		return false
	}
}

// Defines values for CreateAIConfigRequestProvider.
const (
	CreateAIConfigRequestProviderClaude  CreateAIConfigRequestProvider = "claude"
	CreateAIConfigRequestProviderCopilot CreateAIConfigRequestProvider = "copilot"
	CreateAIConfigRequestProviderOllama  CreateAIConfigRequestProvider = "ollama"
	CreateAIConfigRequestProviderOpenai  CreateAIConfigRequestProvider = "openai"
)

// Valid indicates whether the value is a known member of the CreateAIConfigRequestProvider enum.
func (e CreateAIConfigRequestProvider) Valid() bool {
	switch e {
	case CreateAIConfigRequestProviderClaude:
		return true
	case CreateAIConfigRequestProviderCopilot:
		return true
	case CreateAIConfigRequestProviderOllama:
		return true
	case CreateAIConfigRequestProviderOpenai:
		return true
	default:
		return false
	}
}

// Defines values for FieldKind.
const (
	Boolean FieldKind = "boolean"
	Number  FieldKind = "number"
	String  FieldKind = "string"
	Time    FieldKind = "time"
)

// Valid indicates whether the value is a known member of the FieldKind enum.
func (e FieldKind) Valid() bool {
	switch e {
	case Boolean:
		return true
	case Number:
		return true
	case String:
		return true
	case Time:
		return true
	default:
		return false
	}
}

// Defines values for FrameType.
const (
	Logs       FrameType = "logs"
	Table      FrameType = "table"
	TimeSeries FrameType = "time_series"
)

// Valid indicates whether the value is a known member of the FrameType enum.
func (e FrameType) Valid() bool {
	switch e {
	case Logs:
		return true
	case Table:
		return true
	case TimeSeries:
		return true
	default:
		return false
	}
}

// Defines values for UpdateAIConfigRequestProvider.
const (
	Claude  UpdateAIConfigRequestProvider = "claude"
	Copilot UpdateAIConfigRequestProvider = "copilot"
	Ollama  UpdateAIConfigRequestProvider = "ollama"
	Openai  UpdateAIConfigRequestProvider = "openai"
)

// Valid indicates whether the value is a known member of the UpdateAIConfigRequestProvider enum.
func (e UpdateAIConfigRequestProvider) Valid() bool {
	switch e {
	case Claude:
		return true
	case Copilot:
		return true
	case Ollama:
		return true
	case Openai:
		return true
	default:
		return false
	}
}

// AIConfig defines model for AIConfig.
type AIConfig struct {
	// ApiKeySet Whether an API key has been stored (key value never returned)
	ApiKeySet bool             `json:"api_key_set"`
	BaseUrl   string           `json:"base_url"`
	CreatedAt time.Time        `json:"created_at"`
	Id        string           `json:"id"`
	IsActive  bool             `json:"is_active"`
	Model     string           `json:"model"`
	Name      string           `json:"name"`
	Provider  AIConfigProvider `json:"provider"`
	UpdatedAt time.Time        `json:"updated_at"`
}

// AIConfigProvider defines model for AIConfig.Provider.
type AIConfigProvider string

// AIConfigHistory defines model for AIConfigHistory.
type AIConfigHistory struct {
	Action     AIConfigHistoryAction `json:"action"`
	ChangedAt  time.Time             `json:"changed_at"`
	ConfigId   string                `json:"config_id"`
	ConfigName string                `json:"config_name"`
	Id         string                `json:"id"`
	Provider   string                `json:"provider"`
}

// AIConfigHistoryAction defines model for AIConfigHistory.Action.
type AIConfigHistoryAction string

// AIConfigHistoryListResponse defines model for AIConfigHistoryListResponse.
type AIConfigHistoryListResponse struct {
	Data []AIConfigHistory `json:"data"`
}

// AIConfigListResponse defines model for AIConfigListResponse.
type AIConfigListResponse struct {
	Data []AIConfig `json:"data"`
}

// AIConfigResponse defines model for AIConfigResponse.
type AIConfigResponse struct {
	Data AIConfig `json:"data"`
}

// AISettingsData defines model for AISettingsData.
type AISettingsData struct {
	Claude   *ClaudeSettingsResponse  `json:"claude,omitempty"`
	Copilot  *CopilotSettingsResponse `json:"copilot,omitempty"`
	Enabled  bool                     `json:"enabled"`
	Ollama   *OllamaSettingsResponse  `json:"ollama,omitempty"`
	Openai   *OpenAISettingsResponse  `json:"openai,omitempty"`
	Provider string                   `json:"provider"`
}

// BatchQueryItem defines model for BatchQueryItem.
type BatchQueryItem struct {
	// RefId Query identifier (e.g. "A", "B"). Returned in results.
	RefId   string       `json:"ref_id"`
	Request QueryRequest `json:"request"`
}

// BatchQueryRequest defines model for BatchQueryRequest.
type BatchQueryRequest struct {
	Queries []BatchQueryItem `json:"queries"`
}

// BatchQueryResponse defines model for BatchQueryResponse.
type BatchQueryResponse struct {
	Results []BatchQueryResultItem `json:"results"`
}

// BatchQueryResultItem defines model for BatchQueryResultItem.
type BatchQueryResultItem struct {
	Data *QueryResult `json:"data,omitempty"`

	// Error Per-query error message if this query failed.
	Error   *string       `json:"error,omitempty"`
	Inspect *QueryInspect `json:"inspect,omitempty"`
	RefId   string        `json:"ref_id"`
	Stats   *QueryStats   `json:"stats,omitempty"`
}

// ClaudeSettingsInput defines model for ClaudeSettingsInput.
type ClaudeSettingsInput struct {
	// ApiKey Empty string keeps the existing key
	ApiKey  *string `json:"api_key,omitempty"`
	BaseUrl *string `json:"base_url,omitempty"`
	Model   *string `json:"model,omitempty"`
}

// ClaudeSettingsResponse defines model for ClaudeSettingsResponse.
type ClaudeSettingsResponse struct {
	ApiKeySet *bool   `json:"api_key_set,omitempty"`
	BaseUrl   *string `json:"base_url,omitempty"`
	Model     *string `json:"model,omitempty"`
}

// Connection defines model for Connection.
type Connection struct {
	// Config Driver-specific connection configuration
	Config      json.RawMessage    `json:"config"`
	CreatedAt   time.Time          `json:"created_at"`
	CreatedBy   *string            `json:"created_by,omitempty"`
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	IsActive    bool               `json:"is_active"`
	Name        string             `json:"name"`
	Tags        *[]string          `json:"tags,omitempty"`

	// Type Datasource type identifier (e.g. "postgresql", "clickhouse")
	Type      string    `json:"type"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ConnectionHistory defines model for ConnectionHistory.
type ConnectionHistory struct {
	Action         ConnectionHistoryAction `json:"action"`
	ChangedAt      time.Time               `json:"changed_at"`
	ConnectionId   string                  `json:"connection_id"`
	ConnectionName string                  `json:"connection_name"`
	ConnectionType string                  `json:"connection_type"`
	Id             string                  `json:"id"`
}

// ConnectionHistoryAction defines model for ConnectionHistory.Action.
type ConnectionHistoryAction string

// ConnectionHistoryListResponse defines model for ConnectionHistoryListResponse.
type ConnectionHistoryListResponse struct {
	Data []ConnectionHistory `json:"data"`
}

// ConnectionListResponse defines model for ConnectionListResponse.
type ConnectionListResponse struct {
	Data []Connection `json:"data"`
}

// ConnectionResponse defines model for ConnectionResponse.
type ConnectionResponse struct {
	Data Connection `json:"data"`
}

// ConnectionSchemaResponse defines model for ConnectionSchemaResponse.
type ConnectionSchemaResponse struct {
	Data map[string]interface{} `json:"data"`
}

// ConnectionStats defines model for ConnectionStats.
type ConnectionStats struct {
	ActiveCount int64            `json:"active_count"`
	CountByType map[string]int64 `json:"count_by_type"`
	TotalCount  int64            `json:"total_count"`
}

// ConnectionStatsResponse defines model for ConnectionStatsResponse.
type ConnectionStatsResponse struct {
	Data ConnectionStats `json:"data"`
}

// ConnectionTestResponse defines model for ConnectionTestResponse.
type ConnectionTestResponse struct {
	Data ConnectionTestResult `json:"data"`
}

// ConnectionTestResult defines model for ConnectionTestResult.
type ConnectionTestResult struct {
	IsConnected bool       `json:"is_connected"`
	LatencyMs   *int64     `json:"latency_ms,omitempty"`
	Message     string     `json:"message"`
	TestedAt    *time.Time `json:"tested_at,omitempty"`
}

// ConnectionTypesResponse defines model for ConnectionTypesResponse.
type ConnectionTypesResponse struct {
	Data []string `json:"data"`
}

// CopilotSettingsInput defines model for CopilotSettingsInput.
type CopilotSettingsInput struct {
	// ApiKey Empty string keeps the existing key
	ApiKey  *string `json:"api_key,omitempty"`
	BaseUrl *string `json:"base_url,omitempty"`
	Model   *string `json:"model,omitempty"`
}

// CopilotSettingsResponse defines model for CopilotSettingsResponse.
type CopilotSettingsResponse struct {
	ApiKeySet *bool   `json:"api_key_set,omitempty"`
	BaseUrl   *string `json:"base_url,omitempty"`
	Model     *string `json:"model,omitempty"`
}

// CreateAIConfigRequest defines model for CreateAIConfigRequest.
type CreateAIConfigRequest struct {
	ApiKey   *string                       `json:"api_key,omitempty"`
	BaseUrl  *string                       `json:"base_url,omitempty"`
	Model    *string                       `json:"model,omitempty"`
	Name     string                        `json:"name"`
	Provider CreateAIConfigRequestProvider `json:"provider"`
}

// CreateAIConfigRequestProvider defines model for CreateAIConfigRequest.Provider.
type CreateAIConfigRequestProvider string

// CreateConnectionRequest defines model for CreateConnectionRequest.
type CreateConnectionRequest struct {
	Config      map[string]interface{} `json:"config"`
	CreatedBy   *string                `json:"created_by,omitempty"`
	Description *string                `json:"description,omitempty"`
	Name        string                 `json:"name"`
	Tags        *[]string              `json:"tags,omitempty"`
	Type        string                 `json:"type"`
}

// DataFrame defines model for DataFrame.
type DataFrame struct {
	Fields []Field `json:"fields"`

	// FrameType Hint for how the DataFrame should be visualized.
	FrameType FrameType `json:"frame_type"`
	Name      *string   `json:"name,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// Field defines model for Field.
type Field struct {
	// Kind Semantic type of a field, used for rendering (axis selection, formatting).
	Kind FieldKind `json:"kind"`

	// Labels Key-value labels attached to the field (e.g. Prometheus metric labels).
	Labels *map[string]string `json:"labels,omitempty"`
	Name   string             `json:"name"`

	// Type Native database type string (display only).
	Type   *string       `json:"type,omitempty"`
	Values []interface{} `json:"values"`
}

// FieldKind Semantic type of a field, used for rendering (axis selection, formatting).
type FieldKind string

// FrameType Hint for how the DataFrame should be visualized.
type FrameType string

// OllamaSettingsInput defines model for OllamaSettingsInput.
type OllamaSettingsInput struct {
	BaseUrl *string `json:"base_url,omitempty"`
	Model   *string `json:"model,omitempty"`
}

// OllamaSettingsResponse defines model for OllamaSettingsResponse.
type OllamaSettingsResponse struct {
	BaseUrl *string `json:"base_url,omitempty"`
	Model   *string `json:"model,omitempty"`
}

// OpenAISettingsInput defines model for OpenAISettingsInput.
type OpenAISettingsInput struct {
	// ApiKey Empty string keeps the existing key
	ApiKey  *string `json:"api_key,omitempty"`
	BaseUrl *string `json:"base_url,omitempty"`
	Model   *string `json:"model,omitempty"`
}

// OpenAISettingsResponse defines model for OpenAISettingsResponse.
type OpenAISettingsResponse struct {
	ApiKeySet *bool   `json:"api_key_set,omitempty"`
	BaseUrl   *string `json:"base_url,omitempty"`
	Model     *string `json:"model,omitempty"`
}

// QueryInspect defines model for QueryInspect.
type QueryInspect struct {
	// ExecutedQuery Final query after all variable substitution.
	ExecutedQuery string `json:"executed_query"`

	// RawQuery Original template before variable substitution.
	RawQuery string `json:"raw_query"`

	// Variables Full context used for substitution (including built-in __ variables).
	Variables *map[string]interface{} `json:"variables,omitempty"`
}

// QueryRequest defines model for QueryRequest.
type QueryRequest struct {
	Limit *int `json:"limit,omitempty"`

	// Query Raw query template. Server-side {{ variable }} substitution is applied before execution. Built-in variables (__ prefix) are injected automatically from time_range.
	Query     string     `json:"query"`
	TimeRange *TimeRange `json:"time_range,omitempty"`

	// Variables User-defined variables for {{ }} template substitution.
	Variables *map[string]interface{} `json:"variables,omitempty"`
}

// QueryResponse defines model for QueryResponse.
type QueryResponse struct {
	Data    QueryResult   `json:"data"`
	Inspect *QueryInspect `json:"inspect,omitempty"`
	Stats   *QueryStats   `json:"stats,omitempty"`
}

// QueryResult defines model for QueryResult.
type QueryResult struct {
	Frames []DataFrame `json:"frames"`
}

// QueryStats defines model for QueryStats.
type QueryStats struct {
	BytesRead       *int64 `json:"bytes_read,omitempty"`
	ExecutionTimeMs int64  `json:"execution_time_ms"`
	RowsReturned    int64  `json:"rows_returned"`
}

// TestConnectionRequest defines model for TestConnectionRequest.
type TestConnectionRequest struct {
	Config map[string]interface{} `json:"config"`
	Type   string                 `json:"type"`
}

// TimeRange defines model for TimeRange.
type TimeRange struct {
	// From Start of the time range. Accepts ISO 8601 ("2024-04-01T00:00:00Z"), Unix ms as a numeric string ("1712160000000"), or a relative expression ("1 Hours ago").
	From *string `json:"from,omitempty"`

	// To End of the time range. Accepts the same formats as "from", plus "Now".
	To *string `json:"to,omitempty"`
}

// UpdateAIConfigRequest defines model for UpdateAIConfigRequest.
type UpdateAIConfigRequest struct {
	// ApiKey Empty string keeps existing key
	ApiKey   *string                        `json:"api_key,omitempty"`
	BaseUrl  *string                        `json:"base_url,omitempty"`
	Model    *string                        `json:"model,omitempty"`
	Name     *string                        `json:"name,omitempty"`
	Provider *UpdateAIConfigRequestProvider `json:"provider,omitempty"`
}

// UpdateAIConfigRequestProvider defines model for UpdateAIConfigRequest.Provider.
type UpdateAIConfigRequestProvider string

// UpdateAISettingsRequest defines model for UpdateAISettingsRequest.
type UpdateAISettingsRequest struct {
	Claude   *ClaudeSettingsInput  `json:"claude,omitempty"`
	Copilot  *CopilotSettingsInput `json:"copilot,omitempty"`
	Enabled  *bool                 `json:"enabled,omitempty"`
	Ollama   *OllamaSettingsInput  `json:"ollama,omitempty"`
	Openai   *OpenAISettingsInput  `json:"openai,omitempty"`
	Provider *string               `json:"provider,omitempty"`
}

// UpdateConnectionRequest defines model for UpdateConnectionRequest.
type UpdateConnectionRequest struct {
	Config      *map[string]interface{} `json:"config,omitempty"`
	Description *string                 `json:"description,omitempty"`
	IsActive    *bool                   `json:"is_active,omitempty"`
	Name        *string                 `json:"name,omitempty"`
	Tags        *[]string               `json:"tags,omitempty"`
}

// BadGateway defines model for BadGateway.
type BadGateway = ErrorResponse

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// NotImplemented defines model for NotImplemented.
type NotImplemented = ErrorResponse

// ListAIConfigHistoryParams defines parameters for ListAIConfigHistory.
type ListAIConfigHistoryParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListAIConfigHistoryByConfigParams defines parameters for ListAIConfigHistoryByConfig.
type ListAIConfigHistoryByConfigParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListConnectionsParams defines parameters for ListConnections.
type ListConnectionsParams struct {
	// Type Filter by datasource type
	Type *string `form:"type,omitempty" json:"type,omitempty"`

	// IsActive Filter by active status
	IsActive *bool `form:"is_active,omitempty" json:"is_active,omitempty"`

	// CreatedBy Filter by creator
	CreatedBy *string `form:"created_by,omitempty" json:"created_by,omitempty"`
}

// ListConnectionHistoryParams defines parameters for ListConnectionHistory.
type ListConnectionHistoryParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListConnectionHistoryByConnectionParams defines parameters for ListConnectionHistoryByConnection.
type ListConnectionHistoryByConnectionParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateAIConfigJSONRequestBody defines body for CreateAIConfig for application/json ContentType.
type CreateAIConfigJSONRequestBody = CreateAIConfigRequest

// UpdateAIConfigJSONRequestBody defines body for UpdateAIConfig for application/json ContentType.
type UpdateAIConfigJSONRequestBody = UpdateAIConfigRequest

// CreateConnectionJSONRequestBody defines body for CreateConnection for application/json ContentType.
type CreateConnectionJSONRequestBody = CreateConnectionRequest

// TestConnectionConfigJSONRequestBody defines body for TestConnectionConfig for application/json ContentType.
type TestConnectionConfigJSONRequestBody = TestConnectionRequest

// UpdateConnectionJSONRequestBody defines body for UpdateConnection for application/json ContentType.
type UpdateConnectionJSONRequestBody = UpdateConnectionRequest

// QueryConnectionJSONRequestBody defines body for QueryConnection for application/json ContentType.
type QueryConnectionJSONRequestBody = QueryRequest

// BatchQueryConnectionJSONRequestBody defines body for BatchQueryConnection for application/json ContentType.
type BatchQueryConnectionJSONRequestBody = BatchQueryRequest

// UpdateAISettingsJSONRequestBody defines body for UpdateAISettings for application/json ContentType.
type UpdateAISettingsJSONRequestBody = UpdateAISettingsRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all AI provider configs (no api_key values)
	// (GET /ai-configs)
	ListAIConfigs(c *gin.Context)
	// Create an AI provider config
	// (POST /ai-configs)
	CreateAIConfig(c *gin.Context)
	// List all AI config change history (requires statistics_store)
	// (GET /ai-configs/history)
	ListAIConfigHistory(c *gin.Context, params ListAIConfigHistoryParams)
	// Delete an AI config
	// (DELETE /ai-configs/{id})
	DeleteAIConfig(c *gin.Context, id string)
	// Get an AI config by ID
	// (GET /ai-configs/{id})
	GetAIConfig(c *gin.Context, id string)
	// Update an AI config (empty api_key keeps existing)
	// (PUT /ai-configs/{id})
	UpdateAIConfig(c *gin.Context, id string)
	// Set the active AI config (clears others)
	// (POST /ai-configs/{id}/activate)
	ActivateAIConfig(c *gin.Context, id string)
	// List change history for a specific AI config
	// (GET /ai-configs/{id}/history)
	ListAIConfigHistoryByConfig(c *gin.Context, id string, params ListAIConfigHistoryByConfigParams)
	// Get connection statistics
	// (GET /connection-stats)
	GetConnectionStats(c *gin.Context)
	// List supported connection types
	// (GET /connection-types)
	ListConnectionTypes(c *gin.Context)
	// List all connections
	// (GET /connections)
	ListConnections(c *gin.Context, params ListConnectionsParams)
	// Create a connection
	// (POST /connections)
	CreateConnection(c *gin.Context)
	// List all datasource change history (requires statistics_store)
	// (GET /connections/history)
	ListConnectionHistory(c *gin.Context, params ListConnectionHistoryParams)
	// Test a connection config without saving
	// (POST /connections/test)
	TestConnectionConfig(c *gin.Context)
	// Delete a connection
	// (DELETE /connections/{id})
	DeleteConnection(c *gin.Context, id openapi_types.UUID)
	// Get a connection by ID
	// (GET /connections/{id})
	GetConnection(c *gin.Context, id openapi_types.UUID)
	// Update a connection
	// (PUT /connections/{id})
	UpdateConnection(c *gin.Context, id openapi_types.UUID)
	// List change history for a specific datasource
	// (GET /connections/{id}/history)
	ListConnectionHistoryByConnection(c *gin.Context, id openapi_types.UUID, params ListConnectionHistoryByConnectionParams)
	// Execute a query through a connection
	// (POST /connections/{id}/query)
	QueryConnection(c *gin.Context, id openapi_types.UUID)
	// Execute multiple queries through a connection and return all results
	// (POST /connections/{id}/query/batch)
	BatchQueryConnection(c *gin.Context, id openapi_types.UUID)
	// Get datasource schema for a connection
	// (GET /connections/{id}/schema)
	GetConnectionSchema(c *gin.Context, id openapi_types.UUID)
	// Test a connection
	// (POST /connections/{id}/test)
	TestConnection(c *gin.Context, id openapi_types.UUID)
	// Get current AI settings (no secret values)
	// (GET /settings/ai)
	GetAISettings(c *gin.Context)
	// Save AI settings (empty api_key keeps existing value)
	// (PUT /settings/ai)
	UpdateAISettings(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListAIConfigs operation middleware
func (siw *ServerInterfaceWrapper) ListAIConfigs(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListAIConfigs(c)
}

// CreateAIConfig operation middleware
func (siw *ServerInterfaceWrapper) CreateAIConfig(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateAIConfig(c)
}

// ListAIConfigHistory operation middleware
func (siw *ServerInterfaceWrapper) ListAIConfigHistory(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAIConfigHistoryParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListAIConfigHistory(c, params)
}

// DeleteAIConfig operation middleware
func (siw *ServerInterfaceWrapper) DeleteAIConfig(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteAIConfig(c, id)
}

// GetAIConfig operation middleware
func (siw *ServerInterfaceWrapper) GetAIConfig(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAIConfig(c, id)
}

// UpdateAIConfig operation middleware
func (siw *ServerInterfaceWrapper) UpdateAIConfig(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateAIConfig(c, id)
}

// ActivateAIConfig operation middleware
func (siw *ServerInterfaceWrapper) ActivateAIConfig(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ActivateAIConfig(c, id)
}

// ListAIConfigHistoryByConfig operation middleware
func (siw *ServerInterfaceWrapper) ListAIConfigHistoryByConfig(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAIConfigHistoryByConfigParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListAIConfigHistoryByConfig(c, id, params)
}

// GetConnectionStats operation middleware
func (siw *ServerInterfaceWrapper) GetConnectionStats(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetConnectionStats(c)
}

// ListConnectionTypes operation middleware
func (siw *ServerInterfaceWrapper) ListConnectionTypes(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListConnectionTypes(c)
}

// ListConnections operation middleware
func (siw *ServerInterfaceWrapper) ListConnections(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListConnectionsParams

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", c.Request.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter type: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "is_active" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "is_active", c.Request.URL.Query(), &params.IsActive, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter is_active: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "created_by" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "created_by", c.Request.URL.Query(), &params.CreatedBy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter created_by: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListConnections(c, params)
}

// CreateConnection operation middleware
func (siw *ServerInterfaceWrapper) CreateConnection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateConnection(c)
}

// ListConnectionHistory operation middleware
func (siw *ServerInterfaceWrapper) ListConnectionHistory(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListConnectionHistoryParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListConnectionHistory(c, params)
}

// TestConnectionConfig operation middleware
func (siw *ServerInterfaceWrapper) TestConnectionConfig(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.TestConnectionConfig(c)
}

// DeleteConnection operation middleware
func (siw *ServerInterfaceWrapper) DeleteConnection(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteConnection(c, id)
}

// GetConnection operation middleware
func (siw *ServerInterfaceWrapper) GetConnection(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetConnection(c, id)
}

// UpdateConnection operation middleware
func (siw *ServerInterfaceWrapper) UpdateConnection(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateConnection(c, id)
}

// ListConnectionHistoryByConnection operation middleware
func (siw *ServerInterfaceWrapper) ListConnectionHistoryByConnection(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListConnectionHistoryByConnectionParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListConnectionHistoryByConnection(c, id, params)
}

// QueryConnection operation middleware
func (siw *ServerInterfaceWrapper) QueryConnection(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.QueryConnection(c, id)
}

// BatchQueryConnection operation middleware
func (siw *ServerInterfaceWrapper) BatchQueryConnection(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.BatchQueryConnection(c, id)
}

// GetConnectionSchema operation middleware
func (siw *ServerInterfaceWrapper) GetConnectionSchema(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetConnectionSchema(c, id)
}

// TestConnection operation middleware
func (siw *ServerInterfaceWrapper) TestConnection(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.TestConnection(c, id)
}

// GetAISettings operation middleware
func (siw *ServerInterfaceWrapper) GetAISettings(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAISettings(c)
}

// UpdateAISettings operation middleware
func (siw *ServerInterfaceWrapper) UpdateAISettings(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateAISettings(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/ai-configs", wrapper.ListAIConfigs)
	router.POST(options.BaseURL+"/ai-configs", wrapper.CreateAIConfig)
	router.GET(options.BaseURL+"/ai-configs/history", wrapper.ListAIConfigHistory)
	router.DELETE(options.BaseURL+"/ai-configs/:id", wrapper.DeleteAIConfig)
	router.GET(options.BaseURL+"/ai-configs/:id", wrapper.GetAIConfig)
	router.PUT(options.BaseURL+"/ai-configs/:id", wrapper.UpdateAIConfig)
	router.POST(options.BaseURL+"/ai-configs/:id/activate", wrapper.ActivateAIConfig)
	router.GET(options.BaseURL+"/ai-configs/:id/history", wrapper.ListAIConfigHistoryByConfig)
	router.GET(options.BaseURL+"/connection-stats", wrapper.GetConnectionStats)
	router.GET(options.BaseURL+"/connection-types", wrapper.ListConnectionTypes)
	router.GET(options.BaseURL+"/connections", wrapper.ListConnections)
	router.POST(options.BaseURL+"/connections", wrapper.CreateConnection)
	router.GET(options.BaseURL+"/connections/history", wrapper.ListConnectionHistory)
	router.POST(options.BaseURL+"/connections/test", wrapper.TestConnectionConfig)
	router.DELETE(options.BaseURL+"/connections/:id", wrapper.DeleteConnection)
	router.GET(options.BaseURL+"/connections/:id", wrapper.GetConnection)
	router.PUT(options.BaseURL+"/connections/:id", wrapper.UpdateConnection)
	router.GET(options.BaseURL+"/connections/:id/history", wrapper.ListConnectionHistoryByConnection)
	router.POST(options.BaseURL+"/connections/:id/query", wrapper.QueryConnection)
	router.POST(options.BaseURL+"/connections/:id/query/batch", wrapper.BatchQueryConnection)
	router.GET(options.BaseURL+"/connections/:id/schema", wrapper.GetConnectionSchema)
	router.POST(options.BaseURL+"/connections/:id/test", wrapper.TestConnection)
	router.GET(options.BaseURL+"/settings/ai", wrapper.GetAISettings)
	router.PUT(options.BaseURL+"/settings/ai", wrapper.UpdateAISettings)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xc627jOLJ+FYLn/EgAJbF7euYc5F/6NmP0bHdv0rML7DgwaKlsc1oi1SSVxBsY2IfY",
	"J9wnWfCim0XJsmM7PbszGKBjmywWq4pVXxVLesQhT1LOgCmJLx+xAJlyJsF8eEWiH4mCe7LUn0LOFDCl",
	"/yRpGtOQKMrZxW+SM/2dDBeQEP3X/wqY4Uv8Pxcl6Qv7q7x4KwQX124RvFqtAhyBDAVNNTF8qddEblH0",
	"r3/8E2WpVAJIgiKiiOSZCAGFnDEI9QTEBfqagViiGaExRHgVaArX8DUDqY7Ldb7oKsAjpkAwEpt5x+Mi",
	"XxbdgLgDgezyqwB/4Oodz1h0PFY+cIXsknb5UZLGkABTcGQmqgvrEW6ypn01es3ZjM7136ngKQhFreGT",
	"lE6+wHIiwbBYp/rXBagFCEQYuvo0Ql9giRZEoikAQ1JxARE60V/ekTgDxEBrQoDKBIPoFAdYLVPAl3jK",
	"eQyEaflMiYRJJmK9lvtVKkHZXP8YCiAKogkxrMy4SPRfOCIKzhRNoKRYzqGRlxSVExIqegeVXytsJDwC",
	"Pw+MJOD9IRX8jkZgbBxYluDLX3EYkyzSbPEUGKE4wCFPacyV/iqOSULwrYfnLI223OcqwAK+ZlRom/pV",
	"b9pxWuErqOky32NF5FWp1IRd46hkmE9/g9Ac8tx8fqJa60uPFYXWYiqiseRL2libbAz2L8OF+dYnn3BB",
	"2HxLOwgNg5MWc3C/tiq3ZVpV5z00UvJQX7GuJCuq2i57yPxnKlXhABry1xFD/0sVJHKTM1nX5qpYnQhB",
	"lo29GeJdLB6At6cztZmhfnz0X/cGlKJsLt84+vVVna/YsO5rMyqnVHr80rNsImCH+SgAI9MYIr9HdO5q",
	"A/WPZpSPuPOAm+anwEpBVef3P2r5NipzfPp4RVS4+LMGTCMFSVMfAmbOW9RjnpmCaARM0RkFgU7gfH6O",
	"xvhqjAM0xq/G+PQcXbsohyhDAmQWK3nuc0uihGddcjGLFqhqbcOO05JY93YriLC+Y40e3Z+9zuKaBHXY",
	"pGxkZw43HM98rU2stp1RJ9MdeL02M3OOO5nMF9nIZE5wJ1dSIWJOYQ6U62b3CcSZhfdmAEpASjIHRGdI",
	"LaisQX+vpVEmU817H25GbqyRx6wtaEpFlOxF78aMbLFbn3Trbm7E0ky1QtOmrN4mqVoiyyj6ApBKpBaA",
	"4IFKZb9a+iTUiT3bEOFqI/ftRryGrbdEw1txVKSJnsBTIH8SRVSPIfGnygglMlhPJ94IegfiTFsJndGw",
	"moZacpkgDsbUeQnww9mcn7kvdZJzfk3u/2SNeVeMn8+ZLr2CqrHeCu6KpbLMONNtU4ZW7KjIvO6nmiNq",
	"Tij/vG7Vb8qsXw/whaCUSzUXIL/GNhaFMQ2/LHgmYYxP8aEzDTMyR7ZPyCZKY91TPrHHHMIx1pFH5CNa",
	"7aEyJld0v3yjJaWosNRkoLlc/wyjoYc94vimjncG9CWpg/C3D8aelmtUedl+7RtDZTMHXc5/jfwOTORQ",
	"oXmM72AS8ozVjyFl6oeX5RGkTMEchD09GVOT6bI4O36+e9FqMKy4IvEW7KwJojo9qG9unfEe4tqX0fjB",
	"Vw+lfYY+x6kfE46Wwbg7c6JnN/igcuJcXFvqGhMFLFxOkr524bC1P1aDfFrArLJbLrVh/8sU5BaebQPC",
	"6K+AWq3gdwfDW0odz4nDDUopS1AtmXhFpPsRTwlPE8p+BjZXi2qOfoAq9pqNrdc5b1uFU42aLeLpl7E0",
	"6D8xTegpwd3hfidhvzzrkNsnVJ01vBOO9boYZxTiqH8J5Z0e7uN/pskX8biThB6pnVlHwrS20QrxIOfY",
	"t8/6DVhjr0VVZUPt0Azz0be7b9D9Qu1V4kbBvaf2AjAmU4hlF3DpNkz8HpZn9j7NkkJEKRIuIEKKG/9q",
	"hORSwk+CJ6AWkEmUgBI0dJNOz7Fnj+0prDch/UA0wDG30dop2azUufuTiMo0JkvEWbw89RakzCZq5rcp",
	"UDmjNzIv5rcq671TTZ3pG0gIUzS03PIZIlZgAcokRGjGBRLAIrC7IA9UIgmxdUgBsgFfhxOzp9xDusjP",
	"smRq7nDcJoMihvgy0PIwNJj8iTJlWFnwe6PT4hQjueBZHKEpoDsqMxLTv9t6X8EKmcbGM9AEJtIWWQMc",
	"87n0MlEv2LdE+L2Fv5brgQMuWLtP+L0BmJbbkGfEL7XqcNPJPkCY6QhritFNeb6jjMSuUk1mCgQicYzu",
	"iKDaaJHMplJRlenR/ssSct9G+qOgc0NdQZJqwI+mMOMCtqCej5TblULfZXGMTBPHgyp9SHU1dEJZGGeR",
	"NplpRmN1RhmaTArWvN54vVZebD1YF/Ntm55a8VNME+q6OWbEJFXDwWAw8KVCLeK+JvdOj7m8z12nzZmk",
	"EaDHx1Lwq1VdGlQi0+gCUa4juyGtF/Qql08hHHQymaBUwIw+nCIiAFH2m8meEMkUT4iiIYnjJZoJniDj",
	"9QRhczgfM5+SywGbovZnmsC1Gbi7bfwiQZxFMKMMosqOtIE8PmrBFNbaYp0t1rBR8U9J2tfuo3a8N3rq",
	"5VBrUlplrwlpdYzsD2lLcLwJejjCrQy1FLimSwVyIoBEPUsPxVGYGEvtXbIQ/F6vYy+dd6ldNRdeJ+rb",
	"+2eQ6nAJ2y6J0eaMqDzYHvPhiQcyKiKUhoo6+GvpIOth0FUYQqokGt18RP//w2CITsb4xeDFy7PBy7PB",
	"8PNgcGn+/9sYnwboF0YfUCIRkYggliWg0XiOlsd4+H/DF8MfBvY/M4ELRJCA2KJseEgFSGnCyRgP0U88",
	"ExKROR/j0zZfxz2QhkVdO9HfSw0zrfkYbsdGLGMcoDTO9McP/H6MvWv6IMMv5jpmm5LHRhB2EAB2jNa+",
	"LvmUMK/tEO3QIGQR787dQcX0vbcGFZR36QsqJnc3BbWI+nD+auNFc78b5D0XmJqSWJmwPuP+O2b0F74k",
	"cxDo+u3NZ3T1aWSySRXD+u/2pzsQ0k4enA/PB4VOU4ov8Xfng/PvcIBTohaG1wtCz6x0zce5zVi0ZE2/",
	"wCjCl/hnKlXuL0wYqjbivxgM9tY17e1P9DRPf3yvd/W9XdlHsODwot7ubrqssyQhGkObfZmM52qEcst1",
	"7RISnTCOnA+07dLSXNgbXf+KK1K71XbPpUdu9eJy2Q/2ikf7e2rBX8Fe1cOwPh+rhuKGe1dcl9Jeu4aA",
	"VYBf9tFc5VmJfSjbLm864xvablPsKqiej4tF2f2w8Zzkt+j6qGmoqkBo+o+YalnkmaP1MC7/CyrCLhLB",
	"7wcBTsgDTXSU+17nhAll9tPQhyH9C/DZzPaYe1aokvSknKvbIxx4Xz/Dcc691S2ynRfIaRiduKMjkU6b",
	"NLgJ5cQ8QHHa01YeabSyYo5BQdNW3pjva76hJuOXnvIuR6+d0PchBcuBOxDd5yDw2/uPoNo3MDiqc7GW",
	"8dKKrVsmxQNH+xDij6BqEkTTJRq96QgUHmegY3F5VIvG4dJzV4/tOqq6DbCrodZ1U0f5B4o9/lSiV+x5",
	"HvPYOuwc36KsTOtGdQIm58rhSD3p2sYjXeTP8RiIfQhb9AKhK7fqE9zd8RVxA8qk3zZDqGojjIEIibha",
	"gJBbiX8HBPFqWcjsDyTxTSKJNewwM3WiohO7R3Dd/0HUtlf2mZ4Vtd+2ML7enHZARbU11R1OSTpGV/rh",
	"S0RX0Uj5e350K+LT4u3Ojtc6w44jv3oT2oGNXGZpyoWCqCpK5TbbR4p9BSibjm790jJWIDTQiuoN+Djw",
	"eiz3U/tpCdpXcL5fm0wmW+hXu+obixTVpK5VTB8UFy30K11SG4LvEWzu2BlaWLMLv511l18qzdqHLMA0",
	"i5hHLsF4mtu/3SJMRa993Ucv7NR8iuEP1LTVUx/HPt/VN6fsUoLpNhmVXyZ4/UP9rvSgibL/WvbIiXLL",
	"gwT7TJefbBias5p7yJOue6oWPFNIkjvbydfPAvqV4dZixDMV4vo4xaAHhD8O+vxmq3FV41mvxjWAw1Mz",
	"rw0PqW4ozx0cm7RdsD6b5/kPK9LtgmN6F4IawdmUgsrl/gA23yiw6S4IlZDnWR2T1yyL7tKjOEYvKjPd",
	"ewd3jGvvbzmqN6y3hD6zIxz2mlB7U52e9qIXa/kbGutn5K1tl0Yk71heCJ7NF0/wpobOxZSocPG8xlu+",
	"hObgFtx8f9CRzdjzVqD/XltOsljRNAbk3qPkNWpEWORet2iS3/x1RlvZeqmcHsV8O/Y41fz6aw32mRXs",
	"oNdGWlApNFjeXVjulXM9UzQuyhfP5s/qdQv8TRUnjo35G6WJznMrXWvshe2lbe+fyXtoD9tBU3vV4YGv",
	"2jIhgCl0NUK5EEwzpYRQgPL0Uuaj7FHramapyepw7Szrnd+9AmuPDobjl9NuiO1cKBXR1UliddOiGkPY",
	"PFHmu5S7+jRCd0McYNPljy9ISi/uhlh7FkfL29ncfGl2QhiZGzdeuQGrnK7mPdpVqe9ynz4yxWY8NBot",
	"oe59aV5Clev71e3q3wEAAP//P6M4KqdcAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
