/**
 * generate.ts — extension loader 생성기 (frontend)
 *
 * 사용법:
 *   npx tsx meta/scripts/generate.ts [--config default] [--root .]
 *
 * meta/configs/{config}.json 을 읽어
 * core/frontend/src/generated/extension-loader.ts 를 생성합니다.
 *
 * 각 extension의 frontend/package.json 에서 패키지 이름을 읽습니다.
 * frontend/ 디렉토리가 없는 extension은 건너뜁니다.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve, join } from 'node:path';

interface Config {
  name: string;
  extensions: string[];
}

interface PackageJson {
  name: string;
}

function parseArgs(): { config: string; root: string } {
  const args = process.argv.slice(2);
  let config = process.env.SITE_MODE ?? 'default';
  let root = '.';

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--config' && args[i + 1]) config = args[++i];
    if (args[i] === '--root' && args[i + 1]) root = args[++i];
  }

  return { config, root };
}

function readConfig(configPath: string): Config {
  const raw = readFileSync(configPath, 'utf-8');
  return JSON.parse(raw) as Config;
}

function resolvePackageName(root: string, extPath: string): string | null {
  const pkgPath = join(root, 'extensions', extPath, 'frontend', 'package.json');
  if (!existsSync(pkgPath)) return null;

  const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8')) as PackageJson;
  return pkg.name;
}

function writeLoader(outPath: string, configName: string, packages: string[]): void {
  const sorted = [...packages].sort();

  const lines: string[] = [
    '// Code generated by meta/scripts/generate.ts — DO NOT EDIT.',
    `// Config: meta/configs/${configName}.json`,
    '',
  ];

  if (sorted.length > 0) {
    lines.push('// Each import triggers the extension\'s side-effect registration.');
    for (const pkg of sorted) {
      lines.push(`import '${pkg}';`);
    }
    lines.push('');
  }

  writeFileSync(outPath, lines.join('\n'), 'utf-8');
}

function main(): void {
  const { config: configName, root: rootRel } = parseArgs();
  const root = resolve(rootRel);

  const configPath = join(root, 'meta', 'configs', `${configName}.json`);
  const cfg = readConfig(configPath);

  // 각 extension의 frontend package name 수집
  const packages: string[] = [];
  const skipped: string[] = [];

  for (const ext of cfg.extensions) {
    const pkgName = resolvePackageName(root, ext);
    if (pkgName) {
      packages.push(pkgName);
    } else {
      skipped.push(ext);
    }
  }

  // 출력 디렉토리 생성
  const outDir = join(root, 'core', 'frontend', 'src', 'generated');
  mkdirSync(outDir, { recursive: true });

  const outPath = join(outDir, 'extension-loader.ts');
  writeLoader(outPath, configName, packages);

  console.log(`generated ${outPath} (${packages.length} extensions)`);
  if (skipped.length > 0) {
    console.log(`skipped (no frontend): ${skipped.join(', ')}`);
  }
}

main();
