// generate.go — extension loader 생성기
//
// 사용법:
//
//	go run meta/scripts/generate.go [--config default] [--root .]
//
// meta/configs/{config}.json 을 읽어
// core/internal/generated/extensions.go 를 생성합니다.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type Config struct {
	Name       string   `json:"name"`
	Extensions []string `json:"extensions"`
}

func main() {
	configName := flag.String("config", getEnv("SITE_MODE", "default"), "config name (e.g. default, enterprise)")
	rootDir := flag.String("root", ".", "project root directory")
	flag.Parse()

	root, err := filepath.Abs(*rootDir)
	if err != nil {
		fatalf("root path: %v", err)
	}

	// meta/configs/{name}.json 읽기
	configPath := filepath.Join(root, "meta", "configs", *configName+".json")
	cfg, err := readConfig(configPath)
	if err != nil {
		fatalf("read config %s: %v", configPath, err)
	}

	// 출력 디렉토리 생성
	outDir := filepath.Join(root, "core", "internal", "generated")
	if err := os.MkdirAll(outDir, 0755); err != nil {
		fatalf("mkdir %s: %v", outDir, err)
	}

	// extensions.go 생성
	outPath := filepath.Join(outDir, "extensions.go")
	if err := writeGoLoader(outPath, *configName, cfg.Extensions); err != nil {
		fatalf("write %s: %v", outPath, err)
	}

	fmt.Printf("generated %s (%d extensions)\n", outPath, len(cfg.Extensions))
}

func readConfig(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var cfg Config
	if err := json.Unmarshal(data, &cfg); err != nil {
		return nil, err
	}
	return &cfg, nil
}

func writeGoLoader(path, configName string, extensions []string) error {
	sorted := make([]string, len(extensions))
	copy(sorted, extensions)
	sort.Strings(sorted)

	var sb strings.Builder
	sb.WriteString("// Code generated by meta/scripts/generate.go — DO NOT EDIT.\n")
	sb.WriteString(fmt.Sprintf("// Config: meta/configs/%s.json\n", configName))
	sb.WriteString("\n")
	sb.WriteString("package generated\n")

	if len(sorted) > 0 {
		sb.WriteString("\n")
		sb.WriteString("import (\n")
		sb.WriteString("\t// Each blank import triggers the extension's init(),\n")
		sb.WriteString("\t// which calls sdk.RegisterDatasource (or equivalent).\n")
		for _, ext := range sorted {
			sb.WriteString(fmt.Sprintf("\t_ \"data-voyager/extensions/%s\"\n", ext))
		}
		sb.WriteString(")\n")
	}

	return os.WriteFile(path, []byte(sb.String()), 0644)
}

func getEnv(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

func fatalf(format string, args ...any) {
	_, _ = fmt.Fprintf(os.Stderr, "generate: "+format+"\n", args...)
	os.Exit(1)
}
